[tox]
envlist = py312
isolated_build = true

[testenv]
allowlist_externals = poetry
skip_install = true
setenv =
    PYTHONPATH = .
commands_pre =
    poetry install --no-root
commands =
    pytest {posargs:tests/}