[tox]
envlist = py312, lint
isolated_build = true

[testenv]
allowlist_externals = poetry
skip_install = true
passenv = *
setenv =
    PYTHONPATH = .
commands_pre =
    poetry install --no-root
commands =
    pytest --cov {posargs:tests/}

[testenv:lint]
commands =
    poetry run ruff check app/
    poetry run ruff format --check app/